// projects.js - edit this file to add, remove or reorder projects
// grid: "normal" (1x1), "wide" (2x1), "tall" (1x2)
// categories: any combination of ["video", "digital", "research"]
// To add a project: copy one object, paste at the top, fill in the fields

const projects = [
    {
    title: "CANDY CRUSHING",
    categories: ["video"],
    img: "img/candycrushing.webp",
    type: "Video",
    year: "2025",
    video: "https://www.youtube.com/watch?v=Qj2_faegDKM",
    link: "",
    role: "Director",
    desc: "Hyperpop music video: CANDY CRUSHING by Angel Rider",
    grid: "tall",
    hover: "drift",
  },
    {
    title: "Sexlied",
    categories: ["video"],
    img: "img/sexlied.webp",
    type: "Video",
    year: "2022",
    video: "https://www.youtube.com/watch?v=L1pKW69Z7ss",
    link: "",
    role: "Cinematographer",
    desc: "Music video by artist Achan Malonda addressing the decolonization of Black female sexuality via an investigation of the male gaze. Audiovisual installation exhibited at I AM MILLI by Dr. Natasha A. Kelly at the Society for Contemporary Art, Osnabrück, Germany. Featured in the Berliner Zeitung.",
    grid: "normal",
    hover: "cold",
  },
        {
    title: "EuroTrash PopStar",
    categories: ["video"],
    img: "img/eurotrashpopstar.webp",
    type: "Video",
    year: "2022",
    video: "https://www.youtube.com/watch?v=xX7hMJkSQ_8",
    link: "",
    role: "Cinematographer",
    desc: "Music video by hyperpop artist Cowboy Blau.",
    grid: "normal",
    hover: "drift",
  },
    {
    title: "Queens Against Borders",
    categories: ["video", "research"],
    img: "img/qab-12.webp",
    type: "Video",
    year: "2021",
    video: "https://www.youtube.com/watch?v=YdFh4VSrqzs",
    link: "",
    role: "Director",
    desc: "This visual ethnography examines the work of queer performance artists in Berlin and their entanglement with socially constructed notions of race, gender, and sexuality.",
    grid: "normal",
    hover: "vivid",
  },
  {
    title: "Flikli Showreel",
    categories: ["video"],
    img: "img/flikli-blog-animationagencypartner.webp",
    type: "Video",
    year: "2023",
    video: "https://www.youtube.com/watch?v=HP_wptuKCaU",
    link: "",
    role: "Scriptwriter",
    desc: "Flikli is a video production studio specializing in creating animated content for awareness, corporate use, education, marketing, and product or service explainers.",
    grid: "wide",
    hover: "harsh",
  },
  {
    title: "YALLA HAFLA",
    categories: ["video"],
    img: "img/qab-3.webp",
    type: "Video",
    year: "2019",
    video: "https://www.youtube.com/watch?v=bkqbPyBQbIY",
    link: "",
    role: "Producer",
    desc: "YALLA HAFLA is a short film about the collaboration between Darvish, a bellydancer from Syria, and Judy LaDivina, a drag performer from Israel, to put on a monthly show for Berlin's queer community.",
    grid: "normal",
    hover: "cold",
  },
  {
    title: "Crossword",
    categories: ["digital"],
    img: "img/crossword.webp",
    type: "Website",
    year: "2025",
    video: "",
    link: "https://kaialisa.github.io/crossword/",
    desc: "Browser-based crossword puzzle tool built with vanilla JavaScript. Generates a structured data.js file powering a playable, responsive puzzle rendered with scalable SVG graphics. Features include auto-advancing clues, solution row tracking, and mobile touch support.",
    grid: "normal",
    hover: "grayscale",
    textCard: true,
  },
  {
    title: "Rising",
    categories: ["video"],
    img: "img/rising.webp",
    type: "Video",
    year: "2020",
    video: "https://www.beyondtheshort.com/documentary/rising-grizzly",
    link: "",
    role: "Cinematographer",
    desc: "Short documentary about the resilience of the human spirit and the power of unity and connection. Produced by The Tenth Man x Grizzly. Kerry International Film Festival 2021 · Best Inspirational Film, Paris Film Festival 2021 · YDA Shortlist 2021 · Beyond the Short 2020.",
    grid: "normal",
    hover: "grayscale",
  },
  {
    title: "A House Where Our Heart Lies",
    categories: ["video", "research"],
    img: "img/Liebig36.webp",
    type: "Video",
    year: "2021",
    video: "https://vimeo.com/690502725",
    link: "",
    role: "Cinematographer",
    desc: "Directed by Lauren Klinger, this ethnographic film explores a Berlin neighborhood's relationship to the Liebig 34 anarcha-feminist squat, which faces eviction. Premiered at the East Expression Artistic Studies Circle of Udine, Italy.",
    grid: "normal",
    hover: "invert",
  },
  {
    title: "Body as Prosthesis",
    categories: ["video"],
    img: "img/body-as-prosthesis-1.webp",
    type: "Video",
    year: "2020",
    video: "",
    link: "",
    role: "Cinematographer",
    desc: "Jonas Büßecker's work in which he collaborates with performance artists from the Berlin drag community who utilize their bodies as instruments to create alter egos and playful illusions around appearance, gender and power. Exhibited at Hošek Contemporary, Berlin 2020.",
    grid: "normal",
    hover: "vivid",
  },
  {
    title: "Stage Performances",
    categories: ["video"],
    img: "img/qab-7.webp",
    type: "Video",
    year: "2019",
    video: "https://www.youtube.com/watch?v=gZl6SffbIMU&list=PLH6dqxIWMjJFo1PeN8tZfFHmqoYX1UKdx",
    link: "",
    role: "Camera, Editing",
    desc: "A selection of drag performances in Berlin.",
    grid: "normal",
    hover: "cold",
  },
  {
    title: "Pinkwashing",
    categories: ["video"],
    img: "img/pinkwashing-3.webp",
    type: "Video",
    year: "2019",
    video: "",
    link: "",
    role: "Producer",
    desc: "Short film of a live act by Tel Aviv-based drag performer Asis D'Orange examining their relationship with the state. Shown at Hošek Contemporary, Berlin 2019 and The Queer Lens: A Masterclass, RMIT University, Melbourne 2019.",
    grid: "normal",
    hover: "vivid",
  },
  {
    title: "وسام – ضو عيوني – Light of my Eyes",
    categories: ["video"],
    img: "img/Wizzy.webp",
    type: "Video",
    year: "2020",
    video: "",
    link: "",
    role: "Producer",
    desc: "Music video following Syrian performer Wizzy through the heart of Berlin, as he reflects on a distant lover and his journey to Europe.",
    grid: "normal",
    hover: "invert",
  },
  {
    title: "Job Board",
    categories: ["digital"],
    img: "img/JobBoardWhite.webp",
    type: "Website",
    year: "2025",
    video: "",
    link: "",
    desc: "A lightweight job board built with vanilla JavaScript and PapaParse to dynamically load and filter job listings from a CSV file. Features keyword search, state-based filtering with logo icons, remote job tags, and sorting by date. Includes structured schema markup for SEO.",
    grid: "normal",
    hover: "drift",
    textCard: true,
  },
  {
    title: "Climate Change Action Series",
    categories: ["video", "research"],
    img: "img/climate-action-series.webp",
    type: "Video",
    year: "2019",
    video: "",
    link: "",
    role: "Producer",
    desc: "Produced in conjunction with Queens Against Borders featuring keynote speakers Nadja Charaby (Rosa Luxemburg Foundation) and Tonny Nowshin (350.org).",
    grid: "wide",
    hover: "warm",
  },
  {
    title: "Entropie Festival",
    categories: ["video"],
    img: "img/entropie-festival.webp",
    type: "Video",
    year: "2019",
    video: "https://www.youtube.com/watch?v=dam1pNK0o3A",
    link: "",
    role: "Cinematographer",
    desc: "The Entropie festival — where political content, social criticism, and utopia meet theatre and performance.",
    grid: "normal",
    hover: "cold",
  },
  {
    title: "Sustainable Consumption",
    categories: ["research"],
    img: "img/superfoods-1.webp",
    type: "Video",
    year: "2020",
    video: "",
    link: "",
    role: "Director",
    desc: "Research-based film funded by the Berlin University Alliance exploring the interconnectedness of food choice, social inequalities, and ecological degradation.",
    grid: "normal",
    hover: "cold",
  },
  {
    title: "UIkit Magazine Grid Filter",
    categories: ["digital"],
    img: "img/UIKitGridSquare.webp",
    type: "Website",
    year: "2025",
    video: "",
    link: "",
    desc: "Vanilla JavaScript script filtering a grid of magazine-style posts by region and category. Supports multi-select filters, tag-based filtering, and optional search. Fully responsive with UIkit transitions.",
    grid: "normal",
    hover: "warm",
    textCard: true,
  },
  {
    title: "Drag It Up!",
    categories: ["research"],
    img: "img/dragitup.webp",
    type: "Video",
    year: "2021",
    video: "",
    link: "",
    role: "Producer",
    desc: "A week-long youth exchange organized by Critical Queer Solidarity with support from Erasmus+ and the Berlin Senate Department for Culture and Europe. Designed to empower young queer people from Europe, the Middle East and North Africa through creativity, theater and art.",
    grid: "normal",
    hover: "grayscale",
  },
  {
    title: "The Politics of Intersectionality",
    categories: ["research"],
    img: "img/GIP-Logo.webp",
    type: "Video",
    year: "2019",
    video: "",
    link: "",
    role: "Producer",
    desc: "Interview series documenting the inaugural conference of the MA program Gender, Intersectionality and Politics on behalf of the Gender and Diversity Division of Freie Universität Berlin, featuring keynote speakers Dr. Akwugo Emejulu and Dr. Sirma Bilge.",
    grid: "normal",
    hover: "warm",
    logo: true,
  },
  {
    title: "EQUIP",
    categories: ["research"],
    img: "img/equipworkshop.webp",
    type: "Video",
    year: "2022",
    video: "",
    link: "",
    role: "Producer",
    desc: "Equal Opportunities in Higher Education — a DIES-Partnership funded by BMZ and DAAD, collaborating between Freie Universität Berlin, the University of Cape Coast, Ghana, and Kenyatta University, Kenya.",
    grid: "wide",
    hover: "drift",
  },
  {
    title: "Online Magazine",
    categories: ["digital"],
    img: "img/MagazineWhite.webp",
    type: "Website",
    year: "2024",
    video: "",
    link: "",
    desc: "Digitizing print media for web with accessible and responsive layouts.",
    grid: "normal",
    hover: "grayscale",
    textCard: true,
  },
    {
    title: "SO36",
    categories: ["video"],
    img: "img/so36-backstage-1-scaled.webp",
    type: "Image",
    year: "2020",
    video: "",
    link: "",
    role: "",
    desc: "",
    grid: "tall",
    hover: "harsh",
  },
  {
    title: "Flowers From Where You Go",
    categories: ["video"],
    img: "img/flowersfromwhereyougo.webp",
    type: "Video",
    year: "2022",
    video: "",
    link: "",
    role: "Camera",
    desc: "Music video by artist The Somnambulist. Featured in indieRepublik magazine.",
    grid: "wide",
    hover: "grayscale",
  },
  {
    title: "Very Confused",
    categories: ["video"],
    img: "img/VeryConfused.webp",
    type: "Image",
    year: "2019",
    video: "",
    link: "",
    role: "",
    desc: "",
    grid: "normal",
  },
];