#!/bin/bash
cd /d/Freelance/Clients/kaialisa-2026/img

curl -O "https://kaialisa.de/wp-content/uploads/2025/03/flikli-blog-animationagencypartner.webp"
curl -O "https://kaialisa.de/wp-content/uploads/2025/02/sexlied.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/02/flowersfromwhereyougo.jpg"
curl -O "https://kaialisa.de/wp-content/uploads/2025/02/eurotrashpopstar.jpg"
curl -O "https://kaialisa.de/wp-content/uploads/2025/02/qab-12.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/03/Liebig36.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/02/dragitup.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/03/rising.jpg"
curl -O "https://kaialisa.de/wp-content/uploads/2025/02/body-as-prosthesis-1.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/02/Wizzy.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/02/superfoods-1.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/02/pinkwashing-3.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/03/GIP-Logo.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/02/equipworkshop.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/02/climate-action-series.jpg"
curl -O "https://kaialisa.de/wp-content/uploads/2025/02/qab-3.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/02/entropie-festival.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/02/VeryConfused.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/03/so36-backstage-1-scaled.jpg"
curl -O "https://kaialisa.de/wp-content/uploads/2025/03/JobBoardWhite.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/03/UIKitGridSquare.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/02/qab-7.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/06/crossword.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/03/MagazineWhite.png"
curl -O "https://kaialisa.de/wp-content/uploads/2025/03/IMG_3461-scaled.jpg"

echo "Done! Downloaded $(ls | wc -l) files."